/**
 * Parity tests for the ported retrieval layer.
 *
 * The FTS vectors in `fts-golden.json` were GENERATED BY RUNNING THE LIVE PYTHON
 * (`remembering/scripts/turso.py::_escape_fts5_server`) over the same inputs.
 * They are not hand-written expectations — they are blue's actual behaviour,
 * frozen. That is what makes this a parity harness rather than a unit test:
 * regenerate them from Python and any divergence shows up here.
 *
 * docs/mcp-migration.md §3 names FTS escaping as "the highest-value unit test"
 * of the whole port, because a tokenizer difference silently changes which
 * memories come back rather than failing loudly.
 */
import golden from "./fts-golden.json" with { type: "json" };
import { escapeFts5, buildSearch, compositeExpr } from "./turso.ts";

let pass = 0, fail = 0;
const eq = (n: string, g: unknown, w: unknown) =>
  JSON.stringify(g) === JSON.stringify(w)
    ? (pass++, console.log("OK  " + n))
    : (fail++, console.log(`FAIL ${n}\n  got:  ${JSON.stringify(g)}\n  want: ${JSON.stringify(w)}`));

// ---------------------------------------------------------------- FTS parity

console.log(`--- FTS5 escaping: ${golden.length} vectors captured from the Python implementation`);
for (const { in: input, out: expected } of golden) {
  eq(`escapeFts5(${JSON.stringify(input)})`, escapeFts5(input), expected);
}

// ---------------------------------------------------------------- ranking SQL

console.log("\n--- ranking expression");
const nonEpisodic = compositeExpr(false);
const episodic = compositeExpr(true);

eq("bm25 weights are id=0, summary=1.0, tags=1.0",
   nonEpisodic.includes("bm25(memory_fts, 0, 1.0, 1.0)"), true);
eq("priority factor is 0.3 per step",
   nonEpisodic.includes("(1.0 + COALESCE(m.priority, 0) * 0.3)"), true);
eq("recency decay is 0.01/day via julianday",
   nonEpisodic.includes("(1.0 / (1.0 + (julianday('now') - julianday(m.t)) * 0.01))"), true);
// Unset confidence defaults to 0.5, not 0 — a 0 default would silently demote
// every memory written before the confidence signal existed.
eq("confidence factor defaults to 0.5 and scales by 0.15",
   nonEpisodic.includes("(1.0 + COALESCE(m.confidence, 0.5) * 0.15)"), true);
eq("non-episodic omits the access boost", nonEpisodic.includes("access_count"), false);
eq("episodic adds ln(1+access_count)*0.2",
   episodic.includes("(1.0 + ln(1.0 + COALESCE(m.access_count, 0)) * 0.2)"), true);

// ---------------------------------------------------------------- query shape

console.log("\n--- query construction");
const base = buildSearch("turso libsql");
eq("MATCH is the first bound parameter", base.params[0], '"turso"* OR "libsql"*');
eq("limit is the last bound parameter", base.params[base.params.length - 1], 10);
eq("soft-deleted rows are excluded", base.sql.includes("m.deleted_at IS NULL"), true);
// bm25() returns NEGATIVE scores (more negative = better match), so the whole
// composite sorts ASCENDING. Flipping this inverts relevance silently.
eq("ordering is ascending on composite_score",
   base.sql.includes("ORDER BY composite_score ASC"), true);

const capped = buildSearch("x", { n: 5, type: "decision" });
eq("type filter binds after the MATCH", capped.params[1], "decision");
eq("explicit n is threaded through", capped.params[capped.params.length - 1], 5);

const anyTags = buildSearch("x", { tags: ["a", "b"] });
eq("tag_mode any ORs the tag clauses",
   anyTags.sql.includes("WHERE value = ?) OR EXISTS"), true);
const allTags = buildSearch("x", { tags: ["a", "b"], tagMode: "all" });
eq("tag_mode all ANDs the tag clauses",
   allTags.sql.includes("WHERE value = ?) AND EXISTS"), true);
eq("tag params are bound in order", anyTags.params.slice(1, 3), ["a", "b"]);

const windowed = buildSearch("x", { since: "2026-01-01", until: "2026-06-01", conf: 0.7 });
eq("conf/since/until all bind", windowed.params.slice(1, 4), [0.7, "2026-01-01", "2026-06-01"]);

// An empty query must still produce a legal MATCH — an empty expression is an
// FTS5 syntax error, which is why the Python returns the literal '""'.
eq("empty query yields a legal MATCH", buildSearch("   ").params[0], '""');

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
