/**
 * Turso access layer — the green half of the memory backend.
 *
 * Port of `remembering/scripts/turso.py` from muninn-utilities. The porting rule
 * for this file, and the reason the port is tractable at all: **the ranking is
 * server-side SQL, not application code.** BM25, recency decay, priority
 * weighting and the confidence factor are all computed by Turso in both worlds.
 * What follows transcribes SQL strings; it does not reimplement retrieval.
 *
 * Anything that changes a ranked result MUST be byte-compared against the Python
 * implementation before it ships — see `turso.test.ts` and `src/fts-golden.json`,
 * whose vectors were generated by running the live Python over the same inputs.
 */

import { createClient, type Client } from "@libsql/client/web";

export interface Config {
  TURSO_URL: string;
  TURSO_TOKEN: string;
}

export function db(config: Config): Client {
  return createClient({
    url: `libsql://${config.TURSO_URL}`,
    authToken: config.TURSO_TOKEN,
  });
}

// ---------------------------------------------------------------- FTS5 escaping

/**
 * FTS5 keyword operators, stripped so a user query cannot restructure the MATCH.
 * Mirrors `_FTS5_KEYWORDS` in turso.py.
 */
const FTS5_KEYWORDS = new Set(["AND", "OR", "NOT", "NEAR"]);

/** FTS5 special characters. Replaced with spaces, not escaped — matching Python. */
const FTS5_SPECIAL = '"*():^';

/**
 * Escape a raw search string into a safe FTS5 MATCH expression.
 *
 * Direct port of `_escape_fts5_server` (turso.py). Every detail here is
 * load-bearing and pinned by golden vectors:
 *  - special chars become SPACES (so 'a*b' splits into two terms, not 'ab')
 *  - keyword operators are dropped case-insensitively, comparing UPPERCASED
 *  - an empty result is the literal `""`, NOT an empty string — an empty MATCH
 *    is an FTS5 syntax error
 *  - terms are OR-ed, each quoted with a trailing prefix wildcard
 *
 * Note this differs from Sage's `ftsQuery`, which quotes all terms but only
 * prefix-wildcards the last. Do not converge them; they serve different indexes.
 */
export function escapeFts5(query: string): string {
  let escaped = query;
  for (const char of FTS5_SPECIAL) {
    escaped = escaped.split(char).join(" ");
  }

  const words = escaped
    .split(/\s+/)
    .map((w) => w.trim())
    .filter((w) => w.length > 0 && !FTS5_KEYWORDS.has(w.toUpperCase()));

  if (words.length === 0) return '""';

  return words.map((w) => `"${w}"*`).join(" OR ");
}

// ---------------------------------------------------------------- ranking

/** BM25 column weights: id=0, summary=1.0, tags=1.0 (tags raised from 0.5 in v5.1.0, #309). */
const BM25_EXPR = "bm25(memory_fts, 0, 1.0, 1.0)";

/**
 * Confidence quality signal (v5.6.0, #paper-MIA). Ranges 1.0 (conf=0) to 1.15
 * (conf=1.0); unset confidence defaults to 0.5, NOT to 0.
 */
const CONF_FACTOR = "(1.0 + COALESCE(m.confidence, 0.5) * 0.15)";

/**
 * Build the composite ranking expression.
 *
 * Transcribed from turso.py `_fts5_search`. The episodic variant adds an
 * access-pattern boost (v5.1.0, #296).
 */
export function compositeExpr(episodic: boolean): string {
  const base =
    `${BM25_EXPR}` +
    ` * (1.0 + COALESCE(m.priority, 0) * 0.3)` +
    ` * (1.0 / (1.0 + (julianday('now') - julianday(m.t)) * 0.01))` +
    ` * ${CONF_FACTOR}`;
  return episodic
    ? `${base} * (1.0 + ln(1.0 + COALESCE(m.access_count, 0)) * 0.2)`
    : base;
}

export interface SearchOpts {
  n?: number;
  type?: string;
  tags?: string[];
  tagMode?: "any" | "all";
  conf?: number;
  sessionId?: string;
  since?: string;
  until?: string;
  episodic?: boolean;
}

export interface SearchResult {
  sql: string;
  params: unknown[];
}

/**
 * Build the FTS5 search query.
 *
 * Split out from execution so the SQL text itself is testable without a live
 * database — the parity harness diffs generated SQL before it diffs results.
 *
 * ORDER BY composite_score **ASC** is not a typo: SQLite's bm25() returns
 * negative scores where more-negative is a better match, so the whole composite
 * sorts ascending. Flipping this silently inverts relevance.
 */
export function buildSearch(search: string, opts: SearchOpts = {}): SearchResult {
  const {
    n = 10,
    type,
    tags,
    tagMode = "any",
    conf,
    sessionId,
    since,
    until,
    episodic = false,
  } = opts;

  const conditions: string[] = ["m.deleted_at IS NULL"];
  const params: unknown[] = [escapeFts5(search)];

  if (type !== undefined) {
    conditions.push("m.type = ?");
    params.push(type);
  }
  if (tags && tags.length > 0) {
    // Tag membership rides json_each over the stored JSON array, matching Python.
    const clause = tags
      .map(() => "EXISTS (SELECT 1 FROM json_each(m.tags) WHERE value = ?)")
      .join(tagMode === "all" ? " AND " : " OR ");
    conditions.push(`(${clause})`);
    params.push(...tags);
  }
  if (conf !== undefined) {
    conditions.push("COALESCE(m.confidence, 0.5) >= ?");
    params.push(conf);
  }
  if (sessionId !== undefined) {
    conditions.push("m.session_id = ?");
    params.push(sessionId);
  }
  if (since !== undefined) {
    conditions.push("m.t >= ?");
    params.push(since);
  }
  if (until !== undefined) {
    conditions.push("m.t <= ?");
    params.push(until);
  }

  params.push(n);

  const sql = `
        SELECT m.*,
               ${BM25_EXPR} AS bm25_score,
               ${compositeExpr(episodic)} AS composite_score
        FROM memory_fts f
        JOIN memories m ON f.id = m.id
        WHERE memory_fts MATCH ?
          AND ${conditions.join(" AND ")}
        ORDER BY composite_score ASC
        LIMIT ?
    `;

  return { sql, params };
}

export interface MemoryRow {
  id: string;
  type: string;
  t: string;
  summary: string;
  confidence: number | null;
  tags: string;
  refs: string;
  priority: number | null;
  created_at: string;
  source?: string | null;
  composite_score?: number;
}

/** Run an FTS search and return raw rows. */
export async function search(
  client: Client,
  query: string,
  opts: SearchOpts = {},
): Promise<MemoryRow[]> {
  const { sql, params } = buildSearch(query, opts);
  const rs = await client.execute({ sql, args: params as never });
  return rs.rows as unknown as MemoryRow[];
}
